version: '3.1'
services:
  app:
    container_name: kandone-back
    image: springboot-postgresql
    build: ./
    ports:
      - "8080:8080"
    environment:
      KANDONE_DATABASE_USERNAME: ${KANDONE_DATABASE_USERNAME}
      KANDONE_DATABASE_PASSWORD: ${KANDONE_DATABASE_PASSWORD}     
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=kandonedb